const axios = require('axios');
class QualityHoldError extends Error { constructor(message, extra={}) { super(message); this.name='QualityHoldError'; Object.assign(this,extra); } }
function getOpenAiKey(){const key=process.env.OPENAI_API_KEY;if(!key)throw new Error('OPENAI_API_KEY 환경변수가 설정되지 않았습니다.');return key;}
const MIN_GENERATED_BODY_CHARS=900;
const TARGET_BODY_CHARS='1400~2200자';
const BANNED=['주목해보세요','가성비를 자랑','큰 매력','든든한 동반자','추천할 만한 제품','완벽한 선택','최고의 선택','강력 추천','안성맞춤','흡입력을 자랑','가격 대비 성능이 뛰어나'];
const SECTION_EMOJIS=['📌','📊','✨','💡','✅','⚠️','🔍','🎯','🎁'];
function bodyLength(v){return String(v||'').replace(/\s/g,'').length;}
function normalizeBody(v){return String(v||'').replace(/\\r\\n/g,'\n').replace(/\\n/g,'\n').replace(/\r\n?/g,'\n').replace(/[ \t]+\n/g,'\n').replace(/\n{3,}/g,'\n\n').trim();}
function cleanVisibleMarkdown(v){return normalizeBody(v).replace(/^#{1,6}\s+/gm,'').replace(/\*\*([^*\n]+)\*\*/g,'$1').replace(/__([^_\n]+)__/g,'$1').replace(/^[-*_]{3,}\s*$/gm,'').replace(/\n{3,}/g,'\n\n').trim();}
async function callOpenAi(messages,temperature=.55){try{return await axios.post('https://api.openai.com/v1/chat/completions',{model:'gpt-4o-mini',messages,temperature,response_format:{type:'json_object'}},{headers:{Authorization:`Bearer ${getOpenAiKey()}`},timeout:60000});}catch(e){throw new QualityHoldError(`[NAVER BLOG][AI FAILED] OpenAI 호출 실패: ${e.message}`,{cause:e});}}
function parse(resp,keys=[]){let p;try{p=JSON.parse(resp.data?.choices?.[0]?.message?.content);}catch{throw new QualityHoldError('[NAVER BLOG][AI FAILED] JSON 파싱 실패');}for(const k of keys)if(p[k]==null)throw new QualityHoldError(`[NAVER BLOG][AI FAILED] ${k} 누락`);return p;}
function buildContext(e,k){return JSON.stringify({productType:e.productType,productName:e.productName,brand:e.brand,category:e.category,price:e.price,currency:e.currency,seller:e.seller,description:e.description,images:Array.isArray(e.images)?e.images.slice(0,12):[],dataSource:e.dataSource,travel:e.travel||undefined,mainKeyword:k.mainKeyword,subKeywords:k.subKeywords,longTailKeywords:k.longTailKeywords},null,2);}
async function makePlan(ctx){const r=await callOpenAi([{role:'system',content:`너는 상품 팩트체커 겸 네이버 블로그 편집기획자다. 입력에 명시된 사실과 일반적인 구매 선택 기준을 엄격히 구분한다. 제품 고유 사실은 입력에 있는 것만 VERIFIED로 인정한다. BLDC라는 단어 하나만으로 저소음, 고효율, 긴 수명, 강한 흡입력, 배터리 절약을 그 제품 사실로 추론하면 안 된다. 후기 데이터가 없으면 사용자 만족/후기/평가를 절대 만들지 않는다. JSON만 답한다.`},{role:'user',content:`[원본 추출 데이터]\n${ctx}\n\nJSON 설계:\nverifiedFacts: 입력에서 문자 그대로 확인 가능한 제품 고유 사실 배열\nunknownClaims: 확인되지 않아 본문에서 제품 사실로 쓰면 안 되는 주장 배열\nreaderQuestions: 구매자가 실제로 확인할 질문 5~7개\nangle: 이 상품에서 가장 중요한 판단 관점\nsectionIdeas: 실제 사실 기반의 구체적인 소제목 후보 5~8개\nseoTerms: 자연스러운 관련 검색어\nimageRoles: 실제 확보 이미지로 보여주면 좋은 장면 역할 4~7개`}],.25);return parse(r,['verifiedFacts','unknownClaims','readerQuestions','angle','sectionIdeas']);}
function writerPrompt(){return `너는 네이버에서 실제 사람이 운영하는 정보형 쇼핑 블로그의 편집자다. VERIFIED FACTS에 없는 제품 고유 사실을 만들지 않는다. 일반 지식은 제품 사실로 단정하지 않는다. 후기 원문이 없으면 사용자 만족/후기/평가를 만들지 않는다. 입력에 없으면 경량, 저소음, 강력한 흡입력, 높은 효율, 긴 수명, 알레르기, 다양한 바닥 성능, 유지비 절감 등을 제품 사실로 쓰지 않는다. 정보가 충분하면 공백 제외 ${TARGET_BODY_CHARS}를 목표로 쓰되 사실이 부족하면 억지로 분량을 늘리지 말고 최소 ${MIN_GENERATED_BODY_CHARS}자 이상에서 정확성을 우선한다. Markdown ###, ##, **, __를 쓰지 않는다. 소제목은 5~8개, 그중 최소 4개는 📌 📊 ✨ 💡 ✅ ⚠️ 🔍 🎯 🎁 중 문맥에 맞는 이모지로 시작한다. 한 문단 1~3문장과 실제 빈 줄을 사용한다. '특징1/특징2/특징3' 같은 기계적 소제목을 쓰지 않는다. 상품 링크 문구는 작성하지 않는다. [IMAGE: ...] 4~7개를 관련 설명 바로 다음에 분산 배치하고 연속 배치하지 않는다. 제원 4개 이상 VERIFIED이면 [SPEC_CARD: 상품명 핵심 제원] 1개를 핵심정보 직후에 넣는다. 제목에 상품명/메인키워드를 자연스럽게 포함하고 첫 150자 안에 상품명 또는 메인키워드를 1회 사용한다. 광고 상투어를 쓰지 않는다. JSON만 출력: {"titles":[5개],"body":"전체본문"}`;}
async function draft(ctx,plan){const r=await callOpenAi([{role:'system',content:writerPrompt()},{role:'user',content:`[상품 원본]\n${ctx}\n\n[팩트/기획]\n${JSON.stringify(plan,null,2)}\n\nverifiedFacts만 제품 사실로 사용해 완성형 네이버 블로그 글을 써. 정보가 충분하면 1400~2200자를 목표로 하고, 정보가 적으면 허위 내용을 만들지 말고 900자 이상에서 사실성을 우선해. 소제목 최소 4개는 서로 어울리는 이모지로 시작하고 Markdown의 ###와 **는 절대 쓰지 마. 이미지 마커는 관련 문단 사이에 분산해.`}],.62);return parse(r,['titles','body']);}
async function factReview(ctx,plan,current){const r=await callOpenAi([{role:'system',content:`너는 엄격한 광고 원고 팩트체커이자 네이버 블로그 편집자다. 원본으로 입증되지 않는 제품 고유 주장은 삭제하거나 구매 전 확인 항목으로 바꾼다. BLDC→강한 흡입/저소음/효율/내구성 같은 추론과 후기 없는 사용자 만족 표현을 삭제한다. Markdown ###, ##, **, __를 쓰지 않는다. 소제목 중 최소 4개는 📌 📊 ✨ 💡 ✅ ⚠️ 🔍 🎯 🎁 중 문맥에 맞는 이모지로 시작하게 유지한다. 이미지 마커는 관련 문단에 분산한다. 링크는 쓰지 않는다. 분량보다 사실성을 우선하되 가능한 경우 1400자 이상을 유지한다. JSON만 답한다.`},{role:'user',content:`[원본]\n${ctx}\n[검증 사실]\n${JSON.stringify(plan,null,2)}\n[초안]\n${JSON.stringify(current,null,2)}\n\n사실성을 최우선으로 검수하고 네이버에서 바로 읽기 좋은 표시 형태로 반환해. {"titles":[5개],"body":"본문"}`}],.25);return parse(r,['titles','body']);}
async function expand(ctx,plan,current){const r=await callOpenAi([{role:'system',content:'너는 사실을 추가하지 않고 설명 깊이만 보강하는 네이버 블로그 편집자다. Markdown 기호를 쓰지 않고 기존 이모지 소제목 구조를 유지한다. 동일 문장 반복과 링크 생성 금지. JSON만 답한다.'},{role:'user',content:`[원본]\n${ctx}\n[팩트]\n${JSON.stringify(plan,null,2)}\n[현재글]\n${JSON.stringify(current,null,2)}\n현재 ${bodyLength(current.body)}자다. verifiedFacts 외 제품 사실을 추가하지 말고 가능하면 1400~1900자로 확장하되, 사실이 부족하면 억지로 늘리지 말고 900자 이상에서 정확성을 우선해. {"titles":[5개],"body":"본문"}`}],.4);return parse(r,['titles','body']);}
function validateMarkers(body){const lines=normalizeBody(body).split('\n').map(v=>v.trim()).filter(Boolean);let imageCount=0,consecutive=false,lastImage=false;for(const line of lines){const is=/^\[IMAGE:/.test(line);if(is){imageCount++;if(lastImage)consecutive=true;}lastImage=is;}const tail=lines.slice(Math.floor(lines.length*.75));const tailImages=tail.filter(v=>/^\[IMAGE:/.test(v)).length;return{imageCount,consecutive,tailImages};}
function emojiCount(body){return SECTION_EMOJIS.reduce((n,e)=>n+(String(body||'').split(e).length-1),0);}
function hasBanned(body){return BANNED.some(v=>String(body||'').includes(v));}
async function generateTitlesAndBody(extracted,keywords){const ctx=buildContext(extracted,keywords);console.log('[NAVER BLOG][FACT PLAN] 원본 사실/미확인 주장 분리');const plan=await makePlan(ctx);console.log(`[NAVER BLOG][FACT PLAN] verified=${plan.verifiedFacts.length} unknown=${plan.unknownClaims?.length||0}`);let final=await draft(ctx,plan);final.body=cleanVisibleMarkdown(final.body);console.log(`[NAVER BLOG][DRAFT] length=${bodyLength(final.body)} emoji=${emojiCount(final.body)}`);final=await factReview(ctx,plan,final);final.body=cleanVisibleMarkdown(final.body);let len=bodyLength(final.body);if(len<1400){console.log(`[NAVER BLOG][SAFE EXPAND] ${len}자 → 사실 추가 없이 설명 보강 시도`);final=await expand(ctx,plan,final);final.body=cleanVisibleMarkdown(final.body);len=bodyLength(final.body);}if(emojiCount(final.body)<4){console.log('[NAVER BLOG][STYLE REVIEW] 이모지 소제목 부족 → 재편집');final=await factReview(ctx,plan,final);final.body=cleanVisibleMarkdown(final.body);len=bodyLength(final.body);}const markers=validateMarkers(final.body);console.log(`[NAVER BLOG][IMAGE PLAN] count=${markers.imageCount} consecutive=${markers.consecutive} tail=${markers.tailImages} emoji=${emojiCount(final.body)}`);if(hasBanned(final.body)){final=await factReview(ctx,plan,final);final.body=cleanVisibleMarkdown(final.body);len=bodyLength(final.body);}if(len<MIN_GENERATED_BODY_CHARS)throw new QualityHoldError(`사실 기반 본문 최소 길이 미달 (${len}자, 최소 ${MIN_GENERATED_BODY_CHARS}자).`);return{titles:(final.titles||[]).slice(0,5),body:final.body,contentPlan:plan};}
module.exports={generateTitlesAndBody,QualityHoldError,normalizeBody,cleanVisibleMarkdown};
