import express from 'express';
import path from 'node:path';
import crypto from 'node:crypto';
import {fileURLToPath} from 'node:url';
import {mkdir,writeFile,readFile} from 'node:fs/promises';
import{searchStockVideos}from'./stockVideoProvider.js';
import{generateTargetCopy,suggestSearchTerms}from'./japaneseCopyGenerator.js';
import{listTargetProfiles}from'./targetProfiles.js';
import{renderShort,renderThumbnail}from'./shortsRenderer.js';
import{getSettingsStatus,saveSettings}from'./configStore.js';
import{saveMusicBuffer}from'./musicStore.js';
const __dirname=path.dirname(fileURLToPath(import.meta.url)),app=express(),PORT=Number(process.env.PORT||8080),publicDir=path.join(__dirname,'..','public'),profileDir=path.join(publicDir,'profiles');
await mkdir(profileDir,{recursive:true});
app.post('/api/music/upload',express.raw({type:['audio/*','application/octet-stream'],limit:'80mb'}),async(q,r)=>{try{const filename=decodeURIComponent(String(q.headers['x-file-name']||'music.mp3'));const result=await saveMusicBuffer(Buffer.from(q.body||[]),{filename,contentType:String(q.headers['content-type']||'')});r.json(result)}catch(e){console.error('[MUSIC UPLOAD]',e);r.status(400).json({error:e.message})}});
app.post('/api/profile/upload',express.raw({type:['image/*','application/octet-stream'],limit:'12mb'}),async(q,r)=>{try{const original=decodeURIComponent(String(q.headers['x-file-name']||'profile.jpg')),ext=(path.extname(original)||'.jpg').toLowerCase().replace(/[^.a-z0-9]/g,'').slice(0,6)||'.jpg',name=`profile-${crypto.randomUUID()}${ext}`,dest=path.join(profileDir,name);await writeFile(dest,Buffer.from(q.body||[]));r.json({ok:true,url:`/profiles/${name}`,path:dest})}catch(e){console.error('[PROFILE UPLOAD]',e);r.status(400).json({error:e.message})}});
app.use(express.json({limit:'2mb'}));
app.get('/',async(_q,r)=>{try{let html=await readFile(path.join(publicDir,'index.html'),'utf8');if(!html.includes('/social-header-patch.js'))html=html.replace('</body>','<script src="/social-header-patch.js"></script></body>');r.type('html').send(html)}catch(e){r.status(500).send(e.message)}});
app.use(express.static(publicDir));
app.get('/api/health',async(_q,r)=>{const s=await getSettingsStatus();r.json({ok:true,service:'m3-global-shorts',pexels:s.PEXELS_API_KEY.configured,pixabay:s.PIXABAY_API_KEY.configured})});
app.get('/api/targets',(_q,r)=>r.json({targets:listTargetProfiles()}));
app.get('/api/admin/settings',async(_q,r)=>{try{r.json(await getSettingsStatus())}catch(e){r.status(500).json({error:e.message})}});
app.post('/api/admin/settings',async(q,r)=>{try{const a={};for(const k of['PEXELS_API_KEY','PIXABAY_API_KEY'])if(Object.prototype.hasOwnProperty.call(q.body||{},k))a[k]=q.body[k];r.json({ok:true,settings:await saveSettings(a)})}catch(e){r.status(500).json({error:e.message})}});
app.get('/api/search',async(q,r)=>{try{const subject=String(q.query.q||'').trim();if(!subject)return r.status(400).json({error:'q is required'});const terms=suggestSearchTerms(subject),selectedTerm=String(q.query.term||terms[0]),videos=await searchStockVideos(selectedTerm,8);r.json({subject,terms,selectedTerm,videos})}catch(e){r.status(500).json({error:e.message})}});
app.post('/api/copy',(q,r)=>{const{subject,mood='dreamy',duration=20,target='ja'}=q.body||{};r.json(generateTargetCopy({subject,mood,duration:Number(duration)||20,target}))});
app.post('/api/render',async(q,r)=>{try{const{clips,title,captions,style={},target='ja',music=null}=q.body||{};if(!title)return r.status(400).json({error:'title is required'});r.json(await renderShort({clips,title,captions,style:{...style,target},music}))}catch(e){console.error('[RENDER]',e);r.status(500).json({error:e.message})}});
app.post('/api/thumbnail',async(q,r)=>{try{const{clip,title,style={},timestamp=1}=q.body||{};if(!clip?.downloadUrl)return r.status(400).json({error:'clip is required'});if(!title)return r.status(400).json({error:'title is required'});r.json(await renderThumbnail({clip,title,style,timestamp}))}catch(e){console.error('[THUMBNAIL]',e);r.status(500).json({error:e.message})}});
app.get('/admin',(_q,r)=>r.sendFile(path.join(publicDir,'admin.html')));
app.use(async(_q,r)=>{try{let html=await readFile(path.join(publicDir,'index.html'),'utf8');if(!html.includes('/social-header-patch.js'))html=html.replace('</body>','<script src="/social-header-patch.js"></script></body>');r.type('html').send(html)}catch(e){r.status(500).send(e.message)}});
app.listen(PORT,'0.0.0.0',()=>console.log(`m3 Global Shorts listening on :${PORT}`));
