import express from 'express';
import path from'node:path';
import crypto from'node:crypto';
import{fileURLToPath}from'node:url';
import{mkdir,writeFile,readFile}from'node:fs/promises';
import{searchStockVideos}from'./stockVideoProvider.js';
import{generateTargetCopy,suggestSearchTerms}from'./japaneseCopyGenerator.js';
import{listTargetProfiles}from'./targetProfiles.js';
import{renderShort,renderThumbnail}from'./shortsRenderer.js';
import{getSettingsStatus,saveSettings}from'./configStore.js';
import{saveMusicBuffer}from'./musicStore.js';
import{analyzeVideoForMemes}from'./videoMemeAnalyzer.js';
const __dirname=path.dirname(fileURLToPath(import.meta.url)),app=express(),PORT=Number(process.env.PORT||8080),publicDir=path.join(__dirname,'..','public'),profileDir=path.join(publicDir,'profiles'),uploadDir=path.join(publicDir,'uploads'),renderDir=process.env.OUTPUT_DIR||path.join(publicDir,'renders');
const previewFonts={heavy:'/usr/share/fonts/opentype/noto/NotoSansCJK-Bold.ttc',clean:'/usr/share/fonts/opentype/noto/NotoSansCJK-Regular.ttc',serif:'/usr/share/fonts/opentype/noto/NotoSerifCJK-Bold.ttc',wide:'/usr/share/fonts/opentype/noto/NotoSansCJK-Bold.ttc',condensed:'/usr/share/fonts/opentype/noto/NotoSansCJK-Bold.ttc',mono:'/usr/share/fonts/opentype/noto/NotoSansCJK-Bold.ttc',serifWide:'/usr/share/fonts/opentype/noto/NotoSerifCJK-Bold.ttc',mplusBlack:'/usr/share/fonts/opentype/mplus/Mplus1-Black.otf',mplusBold:'/usr/share/fonts/opentype/mplus/Mplus1-Bold.otf',mplusRegular:'/usr/share/fonts/opentype/mplus/Mplus1-Regular.otf',vlGothic:'/usr/share/fonts/truetype/vlgothic/VL-Gothic-Regular.ttf',vlPGothic:'/usr/share/fonts/truetype/vlgothic/VL-PGothic-Regular.ttf',bizGothic:'/usr/share/fonts/truetype/bizud-gothic/BIZUDGothic-Bold.ttf',bizPGothic:'/usr/share/fonts/truetype/bizud-gothic/BIZUDPGothic-Bold.ttf',bizMincho:'/usr/share/fonts/truetype/bizud-mincho/BIZUDMincho-Regular.ttf',ipaGothic:'/usr/share/fonts/opentype/ipafont-gothic/ipag.ttf',ipaPGothic:'/usr/share/fonts/opentype/ipafont-gothic/ipagp.ttf',ipaMincho:'/usr/share/fonts/opentype/ipafont-mincho/ipam.ttf'};
await mkdir(profileDir,{recursive:true});await mkdir(uploadDir,{recursive:true});await mkdir(renderDir,{recursive:true});
function validRenderName(v){const name=path.basename(String(v||''));return/^[a-zA-Z0-9-]+\.(mp4|jpg|jpeg|png)$/i.test(name)?name:''}
function validUploadName(v){const name=path.basename(String(v||''));return/^video-[a-z0-9-]+\.(mp4|mov|m4v|webm|mkv)$/i.test(name)?name:''}
function sendRenderDownload(_req,res,name){const safe=validRenderName(name);if(!safe)return res.status(404).send('render not found');const full=path.join(renderDir,safe);return res.download(full,safe,e=>{if(e&&!res.headersSent)res.status(404).send('file not found')})}
app.post('/api/music/upload',express.raw({type:['audio/*','application/octet-stream'],limit:'80mb'}),async(q,r)=>{try{const filename=decodeURIComponent(String(q.headers['x-file-name']||'music.mp3'));r.json(await saveMusicBuffer(Buffer.from(q.body||[]),{filename,contentType:String(q.headers['content-type']||'')}))}catch(e){console.error('[MUSIC UPLOAD]',e);r.status(400).json({error:e.message})}});
app.post('/api/profile/upload',express.raw({type:['image/*','application/octet-stream'],limit:'12mb'}),async(q,r)=>{try{const original=decodeURIComponent(String(q.headers['x-file-name']||'profile.jpg')),ext=(path.extname(original)||'.jpg').toLowerCase().replace(/[^.a-z0-9]/g,'').slice(0,6)||'.jpg',name=`profile-${crypto.randomUUID()}${ext}`,dest=path.join(profileDir,name);await writeFile(dest,Buffer.from(q.body||[]));r.json({ok:true,url:`/profiles/${name}`})}catch(e){console.error('[PROFILE UPLOAD]',e);r.status(400).json({error:e.message})}});
app.post('/api/video/upload',express.raw({type:['video/*','application/octet-stream'],limit:'600mb'}),async(q,r)=>{try{const original=decodeURIComponent(String(q.headers['x-file-name']||'video.mp4'));if(!Buffer.isBuffer(q.body)||q.body.length<1)return r.status(400).json({error:'영상 파일이 비어 있습니다'});const rawExt=(path.extname(original)||'.mp4').toLowerCase(),ext=['.mp4','.mov','.m4v','.webm','.mkv'].includes(rawExt)?rawExt:'.mp4',name=`video-${crypto.randomUUID()}${ext}`,dest=path.join(uploadDir,name);await writeFile(dest,Buffer.from(q.body));r.json({ok:true,uploadId:name,originalName:original,url:`/uploads/${name}`,downloadUrl:`http://127.0.0.1:${PORT}/uploads/${name}`,size:q.body.length})}catch(e){console.error('[VIDEO UPLOAD]',e);r.status(400).json({error:e.message})}});
app.use(express.json({limit:'3mb'}));
app.get('/api/download',async(q,r)=>sendRenderDownload(q,r,q.query.file));
app.get('/',async(_q,r)=>{try{r.type('html').send(await readFile(path.join(publicDir,'index.html'),'utf8'))}catch(e){r.status(500).send(e.message)}});
app.use(express.static(publicDir));
app.get('/api/font/:key',(q,r)=>{const f=previewFonts[String(q.params.key||'')];if(!f)return r.status(404).end();return r.sendFile(f)});
app.get('/api/health',async(_q,r)=>{const s=await getSettingsStatus();r.json({ok:true,service:'m3-global-shorts',pexels:s.PEXELS_API_KEY.configured,pixabay:s.PIXABAY_API_KEY.configured,openai:s.OPENAI_API_KEY.configured})});
app.get('/api/targets',(_q,r)=>r.json({targets:listTargetProfiles()}));
app.get('/api/admin/settings',async(_q,r)=>{try{r.json(await getSettingsStatus())}catch(e){r.status(500).json({error:e.message})}});
app.post('/api/admin/settings',async(q,r)=>{try{const a={};for(const k of['PEXELS_API_KEY','PIXABAY_API_KEY','OPENAI_API_KEY'])if(Object.prototype.hasOwnProperty.call(q.body||{},k))a[k]=q.body[k];r.json({ok:true,settings:await saveSettings(a)})}catch(e){r.status(500).json({error:e.message})}});
app.post('/api/video/analyze',async(q,r)=>{try{const{uploadId,downloadUrl,duration}=q.body||{};if(!uploadId&&!downloadUrl)return r.status(400).json({error:'업로드 영상을 먼저 선택하세요'});r.json(await analyzeVideoForMemes({publicDir,uploadId,downloadUrl,duration}))}catch(e){console.error('[VIDEO ANALYZE]',e);r.status(500).json({error:e.message})}});
app.get('/api/search',async(q,r)=>{try{const subject=String(q.query.q||'').trim();if(!subject)return r.status(400).json({error:'q is required'});const terms=suggestSearchTerms(subject),selectedTerm=String(q.query.term||terms[0]),videos=await searchStockVideos(selectedTerm,8);r.json({subject,terms,selectedTerm,videos})}catch(e){r.status(500).json({error:e.message})}});
app.post('/api/copy',(q,r)=>{const{subject,mood='dreamy',duration=20,target='ja'}=q.body||{};r.json(generateTargetCopy({subject,mood,duration:Number(duration)||20,target}))});
app.post('/api/export-uploaded',async(q,r)=>{try{const{uploadId,duration,templateState={},captions=[],target='ja',music=null}=q.body||{},name=validUploadName(uploadId);if(!name)return r.status(400).json({error:'업로드 영상을 먼저 선택하세요'});if(!String(templateState?.title?.text||'').trim())return r.status(400).json({error:'title is required'});const clip={downloadUrl:`http://127.0.0.1:${PORT}/uploads/${name}`,duration:Number(duration)||5};const out=await renderShort({clips:[clip],templateState,captions,music});r.json({...out,downloadUrl:`/api/download?file=${encodeURIComponent(out.filename)}`})}catch(e){console.error('[EXPORT UPLOADED]',e);r.status(500).json({error:e.message})}});
app.post('/api/render',async(q,r)=>{try{const{clips,templateState={},captions=[],target='ja',music=null}=q.body||{};if(!String(templateState?.title?.text||'').trim())return r.status(400).json({error:'title is required'});const out=await renderShort({clips,templateState,captions,music});r.json({...out,downloadUrl:`/api/download?file=${encodeURIComponent(out.filename)}`})}catch(e){console.error('[RENDER]',e);r.status(500).json({error:e.message})}});
app.post('/api/thumbnail',async(q,r)=>{try{const{clip,templateState={},timestamp=1}=q.body||{};if(!clip?.downloadUrl)return r.status(400).json({error:'clip is required'});if(!String(templateState?.title?.text||'').trim())return r.status(400).json({error:'title is required'});const out=await renderThumbnail({clip,templateState,timestamp});r.json({...out,downloadUrl:`/api/download?file=${encodeURIComponent(out.filename)}`})}catch(e){console.error('[THUMBNAIL]',e);r.status(500).json({error:e.message})}});
app.get('/admin',(_q,r)=>r.sendFile(path.join(publicDir,'admin.html')));
app.use(async(_q,r)=>{try{r.type('html').send(await readFile(path.join(publicDir,'index.html'),'utf8'))}catch(e){r.status(500).send(e.message)}});
app.listen(PORT,'0.0.0.0',()=>console.log(`m3 Global Shorts listening on :${PORT}`));
